specfile_path: owasp-threat-dragon.spec

files_to_sync:
  - desktop_file.patch
  - optimize-electron-build.patch
  - owasp-threat-dragon.desktop
  - owasp-threat-dragon.spec
  - sources

upstream_package_name: owasp-threat-dragon

downstream_package_name: owasp-threat-dragon

jobs:
  - job: copr_build
    owner: "sparticvs"
    project: "owasp-threat-dragon-unstable"
    trigger: commit
    targets:
      - fedora-all
      - epel-8-x86_64
      - epel-9-x86_64
      - centos-stream-8-x86_64
      - centos-stream-9-x86_64
